config/routes.rb
Fosalud::Application.routes.draw do

  get "reports/index"
  match "/view_reports" => "reports#index", :as => "view_reports"

  get "reports/type_reports"
  match "reports/type_reports/:kind/:title" => "reports#type_reports", :as => "type_reports"

  get "reports/aggressions_by_state"
  match "reports/aggressions_by_state/:kind/:title" => "reports#aggressions_by_state" , :as =>"aggressions_by_state"
  resources :aggression_cases

  resources :human_conditions

  resources :human_records, :only=>[:index] do
    member do
      put  "victim_stabilized"
      get  "active_listening" => "human_records#active_listening"
      put "active_listening" => "human_records#active_listening_perform"
      put  "heal_injuries"
      get :demand
      put :demand, :action => :demand_perform
      get :demand
      put :demand, :action => :demand_perform
      get :actual_status
    end
  end

  resources :humen

  resources :violence_kinds

  resources :system_cases

  resources :incident_kinds

  resources :physical_conditions

  resources :psycho_physio_alterations

  resources :emotional_conditions

  resources :weapon_kinds

  resources :aggression_kinds

  resources :zone_kinds

  resources :ocupations

  resources :civil_states

  resources :pregnancy_states

  resources :educational_levels

  resources :human_documents

  resources :document_types

  resources :cities

  resources :states

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  resources :levels
  resources :roles

  get "main/index"

  root :to => 'main#index'

end

app/models/psycho_physio_alteration.rb
class PsychoPhysioAlteration < ActiveRecord::Base
	has_many :diagnosis_emotional_conditions
  	has_many :diagnoses,:through=>:diagnosis_psycho_physio_alterations
  	attr_accessible :name
  attr_accessible :name
  validates :name,  :presence => true, :uniqueness => true
end

app/controllers/psycho_physio_alterations_controller.rb
class PsychoPhysioAlterationsController < ApplicationController
  # GET /psycho_physio_alterations
  # GET /psycho_physio_alterations.json
  def index
    @psycho_physio_alterations = PsychoPhysioAlteration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @psycho_physio_alterations }
    end
  end

  # GET /psycho_physio_alterations/1
  # GET /psycho_physio_alterations/1.json
  def show
    @psycho_physio_alteration = PsychoPhysioAlteration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @psycho_physio_alteration }
    end
  end

  # GET /psycho_physio_alterations/new
  # GET /psycho_physio_alterations/new.json
  def new
    @psycho_physio_alteration = PsychoPhysioAlteration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @psycho_physio_alteration }
    end
  end

  # GET /psycho_physio_alterations/1/edit
  def edit
    @psycho_physio_alteration = PsychoPhysioAlteration.find(params[:id])
  end

  # POST /psycho_physio_alterations
  # POST /psycho_physio_alterations.json
  def create
    @psycho_physio_alteration = PsychoPhysioAlteration.new(params[:psycho_physio_alteration])

    respond_to do |format|
      if @psycho_physio_alteration.save
        format.html { redirect_to @psycho_physio_alteration, notice: 'Psycho physio alteration was successfully created.' }
        format.json { render json: @psycho_physio_alteration, status: :created, location: @psycho_physio_alteration }
      else
        format.html { render action: "new" }
        format.json { render json: @psycho_physio_alteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /psycho_physio_alterations/1
  # PUT /psycho_physio_alterations/1.json
  def update
    @psycho_physio_alteration = PsychoPhysioAlteration.find(params[:id])

    respond_to do |format|
      if @psycho_physio_alteration.update_attributes(params[:psycho_physio_alteration])
        format.html { redirect_to @psycho_physio_alteration, notice: 'Psycho physio alteration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @psycho_physio_alteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /psycho_physio_alterations/1
  # DELETE /psycho_physio_alterations/1.json
  def destroy
    @psycho_physio_alteration = PsychoPhysioAlteration.find(params[:id])
    @psycho_physio_alteration.destroy

    respond_to do |format|
      format.html { redirect_to psycho_physio_alterations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/psycho_physio_alterations_helper.rb
module PsychoPhysioAlterationsHelper
end

app/views/psycho_physio_alterations/_form.html.erb
<%= simple_form_for @psycho_physio_alteration, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                psycho_physio_alterations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/psycho_physio_alterations/edit.html.erb
<%- model_class = PsychoPhysioAlteration -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/psycho_physio_alterations/index.html.erb
<%- model_class = PsychoPhysioAlteration -%>
<div class="page-header">
  <h1><%#=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <h1>Alteraciones psico-fisiologicas</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @psycho_physio_alterations.each do |psycho_physio_alteration| %>
      <tr>
        <td><%= link_to psycho_physio_alteration.id, psycho_physio_alteration_path(psycho_physio_alteration) %></td>
        <td><%= psycho_physio_alteration.name %></td>
        <td><%=l psycho_physio_alteration.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_psycho_physio_alteration_path(psycho_physio_alteration), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      psycho_physio_alteration_path(psycho_physio_alteration),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_psycho_physio_alteration_path,
            :class => 'btn btn-primary' %>

app/views/psycho_physio_alterations/new.html.erb
<%- model_class = PsychoPhysioAlteration -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/psycho_physio_alterations/show.html.erb
<%- model_class = PsychoPhysioAlteration -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @psycho_physio_alteration.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              psycho_physio_alterations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_psycho_physio_alteration_path(@psycho_physio_alteration), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              psycho_physio_alteration_path(@psycho_physio_alteration),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>