config/routes.rb
Fosalud::Application.routes.draw do

  get "reports/index"
  match "/view_reports" => "reports#index", :as => "view_reports"

  get "reports/type_reports"
  match "reports/type_reports/:kind/:title" => "reports#type_reports", :as => "type_reports"

  get "reports/aggressions_by_state"
  match "reports/aggressions_by_state/:kind/:title" => "reports#aggressions_by_state" , :as =>"aggressions_by_state"
  resources :aggression_cases

  resources :human_conditions

  resources :human_records, :only=>[:index] do
    member do
      put  "victim_stabilized"
      get  "active_listening" => "human_records#active_listening"
      put "active_listening" => "human_records#active_listening_perform"
      put  "heal_injuries"
      get :demand
      put :demand, :action => :demand_perform
      get :demand
      put :demand, :action => :demand_perform
      get :actual_status
    end
  end

  resources :humen

  resources :violence_kinds

  resources :system_cases

  resources :incident_kinds

  resources :physical_conditions

  resources :psycho_physio_alterations

  resources :emotional_conditions

  resources :weapon_kinds

  resources :aggression_kinds

  resources :zone_kinds

  resources :ocupations

  resources :civil_states

  resources :pregnancy_states

  resources :educational_levels

  resources :human_documents

  resources :document_types

  resources :cities

  resources :states

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  resources :levels
  resources :roles

  get "main/index"

  root :to => 'main#index'

end

app/models/human_record.rb
class HumanRecord < ActiveRecord::Base
  
  belongs_to :aggression_case
  belongs_to :educational_level
  belongs_to :civil_state
  belongs_to :pregnancy_state
  belongs_to :ocupation
  belongs_to :city
  belongs_to :violence_kind
  belongs_to :system_case
  belongs_to :human

  has_many :human_record_aggressions
  has_many :aggressions,:through=>:human_record_aggressions
  has_many :aggressors #
  has_one  :diagnosis
  
  attr_accessible :state, :er, :legal_rep_name, :legal_rep_last_name, :aggression_ids, :diagnosis, :emotional_condition_ids, :psycho_physio_alteration_ids
  attr_accessible :educational_level_id, :civil_state_id, :pregnancy_state_id, :ocupation_id, :city_id, :violence_kind_id, :system_case_id, :human_id
  attr_accessible :aggression_case_id
  attr_accessible :name, :last_name, :sex, :age
  attr_accessible :aggressors_attributes, :diagnosis_attributes

  accepts_nested_attributes_for :aggressors, allow_destroy: true

  attr_accessor :name, :last_name, :sex, :age

  #after_find :set_human_properties
  before_create :create_human
  after_create :start_process

  

  def set_human_properties
    name = human.name rescue ""
  end

  def create_human
    h = Human.new(:name => name, :last_name => last_name, :sex => sex, :age => age)
    h.save
    self.human_id = h.id
  end

  def start_process
    if er
      crisis
    else
      active_listening
    end
  end

  def self.medical_assistance_list
    where(:state => "medical_assistance").order("er DESC, id ASC")
  end

  def translate_state
    return case state
        when "psicological_crisis"
                  "Crisis"
        when "psicological_attention"
                  "Escucha Activa"
        when "registration"
                  "Toma de datos"
        when "medical_atention"
                  "Atencion medica"
        when "legal_atention"
                  "Atencion legal"
        when "following"
                  "Caso en seguimiento"
    end          
  end

  #--------Estados----------
  #registration=>Registro de la victima
  #psicological_crisis => Crisis nerviosa al momento de recivir a la victima
  #psicological_atention => Session de escucha Activa
  #medical_atention => Atencion y Diagnostico medico
  #legal_atention => Toma de datos del agresor y procedimiento de acciones legales

  #--------Eventos------------
  #crisis=> paso inmediato de registro a atencion de crisis psicologica en el momento que se recive a la victima si en dado caso esta en crisis
  #victim_stabilized=> Paso de crisis psicologica a escucha activa cuando la victima esta estable osea no esta nerviosa o alterada
  #active_listening=> Session de escucha activa la victima relata su historia y se procede a captar los detalles del hecho y el diagnostico psicologico
  #                   Tambien se procede a hacer el diagnostico psicologico y phsicofisiologico
  #                   Aqui se llena la parte que esta abajo del registro de los datos de la persona
  #heal_injuries=>  Diagnostico y tratamiento medico va despues de la escucha activa
  #                 Por el momento este solo debe ser un put y cambio de estado porque no se posee que informacion se debe suministrar
  #demand=>Procedimientos legales, Aqui se toman los datos del agresor, su relacion con la victima y si procedera a poner demanda o no

  state_machine initial: :registration do
    # Si la victima no esta en crisis nerviosa 
    event :crisis do
      transition :registration => :psicological_crisis   
    end

    event :victim_stabilized do
      transition  :psicological_crisis => :psicological_attention  
    end

    event :active_listening do        
      transition :registration => :psicological_attention   
    end
    
    event :heal_injuries do  
      transition :psicological_attention => :medical_attention
    end 
    
    event :demand do   
      transition :medical_attention => :legal_attention 
    end   

    event :end_and_follow do
      transition :legal_atenttion => :following
    end
  end

  ########################################### QUERIES
  scope :active_cases, where("state <> 'registration' AND violence_kind_id=1").order("id ASC")
  scope :active_cases_for_demand, where(:state => "legal_attention",:violence_kind_id=>1).order("id ASC")
  scope :active_cases_for_heal_injuries, where(:state => "medical_attention",:violence_kind_id=>1).order("id ASC")
  scope :active_cases_for_active_listening, where(:state => "psicological_attention",:violence_kind_id=>1).order("id ASC")
  scope :active_cases_for_crisis, where(:state => "psicological_crisis",:violence_kind_id=>1).order("id ASC")
  scope :active_cases_for_psicologist, where(:state => ["psicological_crisis","psicological_attention"],:violence_kind_id=>1).order("id ASC")
  scope :registered_cases, where(:state => "registration",:violence_kind_id=>1).order("id ASC")

end

app/controllers/human_records_controller.rb
class HumanRecordsController < ApplicationController
  
  def index
    if can? :read, HumanRecord
      @human_records = current_user.get_cases

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @human_records }
      end
    else
      redirect_to root_url
    end
  end

  def victim_stabilized
  	@human_record = HumanRecord.find(params[:id])
  	if @human_record.can_victim_stabilized?
  		@human_record.victim_stabilized
  		msg = 'La victima fue remitida a escucha activa'
  	else
  		msg = 'La victima no se pudo remitir a escucha activa'
  	end
  	respond_to do |format|
  		format.html{ redirect_to human_records_path,  notice: msg}
  		format.json{render json: {notice: msg}, status: :created, location: @human_record}
  	end
  end

  def active_listening
    @human_record = HumanRecord.find(params[:id])
  	@system_case = @human_record.system_case
    @aggressions_list = Aggression.grouped_by_kind
  end

  def active_listening_perform
    params[:human_record][:agressions].delete("") if params[:human_record] and params[:human_record][:agressions]
    params[:human_record][:diagnosis][:emotional_conditions].delete("") if params[:human_record] and params[:human_record][:diagnoses] and params[:human_record][:diagnoses][:emotional_conditions]
    params[:human_record][:diagnosis][:psycho_physio_alterations].delete("") if params[:human_record] and params[:human_record][:diagnosis] and params[:human_record][:diagnosis][:psycho_physio_alterations]
    diagnosis_params =  params[:human_record].delete(:diagnosis)
    @diagnosis = Diagnosis.new(diagnosis_params) if !diagnosis_params.nil?
    @human_record = HumanRecord.find(params[:id])
    @system_case = @human_record.system_case
    ActiveRecord::Base.transaction do
      saved = @diagnosis ? @diagnosis.save : false
      if saved
        puts "guardo nuevo diagnosis"
        @human_record.diagnosis = @diagnosis
        saved = @human_record.save
        if saved
          saved = @human_record.can_heal_injuries?
          if saved 
            saved = @system_case.update_attributes(params[:system_case]) 
            if saved
              saved = @human_record.update_attributes(params[:human_record]) 
              if !saved
                @fail_type = "human_record_update"
              end
            else
              @fail_type = "system_case_update"
            end
          else
            @fail_type = "state"
          end
        else
          @fail_type = "human_record_diagnosis"
        end
      else
        puts "no guardo nuevo diagnosis"
        @fail_type = "diagnosis"
      end

      if saved
        @human_record.heal_injuries
        respond_to do |format|
          format.html { redirect_to human_records_path, notice: 'La victima fue remitida a tratamiento medico existosamente' }
        end
        return
      else
        raise ActiveRecord::Rollback
      end
    end
    puts @fail_type
    if @fail_type !="state"
      @aggressions_list = Aggression.grouped_by_kind  
      respond_to do |format|
        format.html { render action: "active_listening" }
      end
    else
      respond_to do |format|
        format.html { redirect_to human_records_path, notice: 'La victima ya fue remitida a tratamiento medico' }
      end
    end
    
  end

  def heal_injuries
  	@human_record = HumanRecord.find(params[:id])
  	if @human_record.can_demand?
  		@human_record.demand
  		msg = 'La victima fue remitida con el trabajador social para asistencia legal en su caso'
  	else
  		msg = 'La victima no se pudo remitir el trabajador social'
  	end
  	respond_to do |format|
  		format.html{ redirect_to human_records_path,  notice: msg}
  		format.json{render json: {notice: msg}, status: :created, location: @human_record}
  	end
  end

  def demand
    @human_record = HumanRecord.find(params[:id])
    @system_case = @human_record.system_case
    @system_case.human_records.build

    #@educational_levels = EducationalLevel.order("name ASC")
    #@civil_states = CivilState.order("name ASC")
    #@ocupations = Ocupation.order("name ASC")
    #@cities = City.order("name ASC")
    @violence_kinds = ViolenceKind.all_except_victim.order("name ASC")
    @human_conditions = HumanCondition.order("name ASC")
    @weapons = WeaponKind.order("name ASC")
  end

  def demand_perform
    #@human_record = HumanRecord.find(params[:id])
    #@system_case = @human_record.system_case
    @system_case = SystemCase.find(params[:id])

    @human_record = HumanRecord.find(params[:human_record_id])
    @human_record.end_and_follow

    if @system_case.update_attributes(params[:system_case])
      redirect_to actual_status_human_record_path(@human_record.id)
      #redirect_to human_records_path, :notice => "La asistencia legal ha sido guardada"
    else
      respond_to do |format|
        format.html { render action: "demand" }
        format.json { render json: @system_case.errors, status: :unprocessable_entity }
      end
    end    
  end

  def actual_status
    @human_record = HumanRecord.find(params[:id])
    @system_case = @human_record.system_case
    @human_records = @system_case.human_records.where("id <> ?", @human_record.id)
  end

end

app/helpers/human_records_helper.rb
module HumanRecordsHelper

end

app/views/human_records/_aggressor.html.erb
<fieldset>
	<%= render :partial => 'system_cases/human', :locals => { f: f } %>

	<%= f.association :physical_condition, :label => "Condicion fisica" %>
	<%= f.input :prior_criminal, :label => "Antecedentes penales" %>
	<%= f.input :aftermath_war, :label => "Secuela de guerra" %>
	<%= f.input :violence_witness, :label => "Testigo de violencia" %>
	<%= f.input :sexual_assault_antecedent, :label => "Antecedentes de agresion sexual" %>

	<%= f.input :educational_level_id, :label => "Nivel educativo", collection: @educational_levels, :include_blank => false %>
	<%= f.input :civil_state_id, :label => "Estado civil", collection: @civil_states, :include_blank => false %>
	<%= f.input :ocupation_id, :label => "Ocupacion", collection: @ocupations, :include_blank => false %>
	<%= f.input :city_id, :label => "Municipio de procedencia", collection: @cities, :include_blank => false %>
	<%= f.input :violence_kind_id, :label => "Rol", collection: @violence_kinds, :include_blank => false %>

	<h4>Condiciones</h4>
	<%= f.input :human_condition_aux, :label => "Condicion", :input_html => { :class => "use_as_tag input-large", :multiple => "true" }, :collection => @human_conditions %>

	<%#= f.fields_for :aggressor_human_conditions do |hc| %>
		<%#= hc.input :human_condition, :label => "Condicion", :input_html => { :class => "human_condition" } %>
		<%#= render :partial => "aggressor_human_condition", f: hc %>
	<%# end %>

	<%#= link_to_add_fields "Agregar condicion", f, :aggressor_human_conditions %>

	<h4>Armas</h4>

	<%= f.fields_for :weapons do |w| %>
		<%= render :partial => "weapon", f: w %>
	<% end %>

	<%= link_to_add_fields "Agregar arma", f, :weapons %>

	<br />

  	<%= link_to "Eliminar involucrado", '#', class: "remove_fields" %>

	<hr />
</fieldset>

app/views/human_records/_aggressor_human_condition.html.erb
<%= f.association :human_condition, :label => "Condicion" %>
<%= link_to "Eliminar condicion", '#', class: "remove_fields" %>

<hr />

app/views/human_records/_diagnoses.html.erb
<fieldset>
	<legend>Diagonostico</legend>
	<%=f.input :physical_disability, label: "Discapacidad Física", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
	<%=f.input :mental_disability, label: "Discapacidad Mental", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
	<%=f.input :violence_witness, label: "Testigo de violencia", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
	<%=f.input :sexual_assault_antecedent, label: "Antecedente de agressión sexual", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
	<%=f.input :diagnosis_description, label: "Descripcion del diagnostico", as: :text, :input_html => { :cols => 500, :rows => 10 }%>
	<div class="aggression-type-field">
		<%=f.input :emotional_condition_ids, collection: EmotionalCondition.all, :label=>"Condiciones emocionales",:input_html => { :class => "use_as_tag input-large", :multiple => "true" }%>
	</div>


	<div class="aggression-type-field">
		<%=f.input :psycho_physio_alteration_ids, collection: PsychoPhysioAlteration.all, :label=>"Alteracions psicofisiologicas",:input_html => { :class => "use_as_tag input-large", :multiple => "true" }%>
	</div>

</fieldset>

app/views/human_records/_human_record.html.erb
<div class="<%= !f.object.id.nil? ? 'hide_block' : '' %>">
	<fieldset>
		<%= render :partial => 'system_cases/human', :locals => { f: f } %>

		<%= f.association :educational_level, :label => "Nivel educativo", :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
		<%= f.association :civil_state, :label => "Estado civil", :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
		<%= f.association :ocupation, :label => "Ocupacion", :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
		<%= f.association :city, :label => "Municipio de procedencia", :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
		<%#= f.association :violence_kind, :label => "Rol", :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
		<%= f.input :violence_kind_id, :label => "Rol", collection: @violence_kinds, :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>

		<% f.object.aggressors.build %>
		<%= f.fields_for :aggressors do |a_builder| %>
			<%= a_builder.input :prior_criminal, label: "Antecedentes penales", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
			<%= a_builder.input :aftermath_war, label: "Secuela de guerra", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
			<%= a_builder.input :violence_witness, label: "Testigo de violencia", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>
			<%= a_builder.input :sexual_assault_antecedent, label: "Antecedentes de agresion sexual", as: :radio_buttons, collection: [['Si', true], ['No', false]], checked: false, item_wrapper_class: 'inline' %>

			<%#= a_builder.input :educational_level_id, :label => "Nivel educativo", collection: @educational_levels, :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
			<%#= a_builder.input :civil_state_id, :label => "Estado civil", collection: @civil_states, :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
			<%#= a_builder.input :ocupation_id, :label => "Ocupacion", collection: @ocupations, :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
			<%#= a_builder.input :city_id, :label => "Municipio de procedencia", collection: @cities, :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>
			<%#= a_builder.input :violence_kind_id, :label => "Rol", collection: @violence_kinds, :include_blank => false, :input_html => { :class => "use_as_tag input-large" } %>

			<%= a_builder.input :human_condition_aux, :label => "Condicion", :input_html => { :class => "use_as_tag input-large", :multiple => "true" }, :collection => @human_conditions %>

			<%= a_builder.input :weapon_aux, :label => "Armas", :input_html => { :class => "use_as_tag input-large", :multiple => "true" }, :collection => @weapons %>
		<% end %>

		<br />

		<%= link_to "Eliminar involucrado", '#', class: "remove_fields" %>
	</fieldset>

	<hr />
</div>

<script type="text/javascript">
	$(function() {
		$(".use_as_tag").select2(); 
	});
</script>

app/views/human_records/_human_record_aggressions.html.erb
<fieldset>
	<legend>Agresiones realizadas</legend>
	<%@aggressions_list.each do |key, value|%>
		<div class="aggression-type-field">
			<%=f.input :aggression_ids, collection: value, :label=>key.to_s.capitalize.gsub("_"," "),:input_html => { :class => "use_as_tag input-large", :multiple => "true" }%>
		</div>
	<%end%>
</fieldset>

app/views/human_records/_system_case.html.erb
<fieldset>
		<legend>Detalles de los hechos</legend>
	<div class="control-group">
    	<%= label :system_case, :city_id, "Municipio del suceso", :class => 'control-label' %>
	    <div class="controls">
	  		<%= collection_select :system_case, :city_id, City.all,:id, :name, :include_blank => false%>
	    </div>
  	</div>
  	<div class="control-group">
    	<%= label :system_case, :zone_kind_id, "Zona", :class => 'control-label' %>
	    <div class="controls">
	  		<%= collection_select :system_case, :zone_kind_id, ZoneKind.all,:id, :name, :include_blank => false%>
	    </div>
  	</div>
  	<div class="control-group">
    	<%= label :system_case, :agression_date, "Fecha de agresion", :class => 'control-label' %>
	    <div class="controls">
	  		<%= datetime_select :system_case, :aggression_date %>
	    </div>
  	</div>
  	<div class="control-group">
    	<%= label :system_case, :recidivism, "Reincidencia", :class => 'control-label' %>
	    <div class="controls">
	  		<%= check_box :system_case, :recidivism %>
	    </div>
  	</div>
  	<div class="control-group">
    	<%= label :system_case, :complaint, "Denuncia", :class => 'control-label' %>
	    <div class="controls">
	  		<%= check_box :system_case, :complaint %>
	    </div>
  	</div>
</fieldset>

app/views/human_records/_weapon.html.erb
<%= f.association :weapon_kind, :label => "Tipo de arma" %>
<%= link_to "Eliminar arma", '#', class: "remove_fields" %>

<hr />

app/views/human_records/active_listening.html.erb
<%= simple_form_for @human_record,:url=>active_listening_human_record_path, :html => { :class => 'form-horizontal' } do |f| %>	
	<%= render 'system_case' %>
	
	<%= render 'human_record_aggressions', f: f %>

	<%= f.fields_for :diagnosis do |builder| %>
		<%= render 'diagnoses', f: builder %>
	<%end%>

	<div class="form-actions">
    <%= f.button :submit, "Guardar", :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), human_records_path, :class => 'btn' %>
  </div>
<%end%>

app/views/human_records/actual_status.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Expediente: " + @human_record.human.full_name %></h1>
</div>

<h3>Datos del caso</h3>

<dl class="dl-horizontal">
  <dt><strong>Caso:</strong></dt>
  <dd>
  	<%= link_to "##{@system_case.id}", system_case_path(@system_case) %>
  </dd>
  <dt><strong>Municipio:</strong></dt>
  <dd><%= @system_case.city.name %></dd>
  <dt><strong>Tipo de zona:</strong></dt>
  <dd><%= @system_case.zone_kind.name %></dd>
  <dt><strong>Fecha de agresion:</strong></dt>
  <dd><%= @system_case.aggression_date.strftime("%d/%m/%Y") %></dd>
  <dt><strong>Reincidencia:</strong></dt>
  <dd><%= @system_case.recidivism ? "Si" : "No" %></dd>
  <dt><strong>Denuncia:</strong></dt>
  <dd><%= @system_case.complaint ? "Si" : "No" %></dd>
</dl>

<hr />

<h3>Datos de la victima</h3>

<dl class="dl-horizontal">
	<dt>
	  <strong>Nombre</strong>
	</dt>
	<dd>
	  <%= link_to @human_record.human.full_name, actual_status_human_record_path(@human_record) %>
	</dd>
	<dt>
	  <strong>Edad</strong>
	</dt>
	<dd>
	  <%= @human_record.human.age %>
	</dd>
	<dt>
	  <strong>Sexo</strong>
	</dt>
	<dd>
	  <%= @human_record.human.sex ? "Femenino" : "Masculino" %>
	</dd>
	<dt>
	  <strong>Estado</strong>
	</dt>
	<dd>
	  <%= @human_record.translate_state %>
	</dd>
	<dt>
	  <strong>Rol</strong>
	</dt>
	<dd>
	  <%= @human_record.violence_kind.name %>
	</dd>
</dl>

<hr />

<h3>Otros Involucrados</h3>

<% @human_records.each do |human_record| %>
  <dl class="dl-horizontal">
    <dt>
      <strong>Nombre</strong>
    </dt>
    <dd>
      <%= link_to human_record.human.full_name, actual_status_human_record_path(human_record) %>
    </dd>
    <dt>
      <strong>Edad</strong>
    </dt>
    <dd>
      <%= human_record.human.age %>
    </dd>
    <dt>
      <strong>Sexo</strong>
    </dt>
    <dd>
      <%= human_record.human.sex ? "Femenino" : "Masculino" %>
    </dd>
    <dt>
      <strong>Estado</strong>
    </dt>
    <dd>
      <%= human_record.translate_state %>
    </dd>
    <dt>
      <strong>Rol</strong>
    </dt>
    <dd>
      <%= human_record.violence_kind.name %>
    </dd>
  </dl>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), human_records_path, :class => 'btn'  %>
</div>

app/views/human_records/demand.html.erb
<%= simple_form_for @system_case, :url => demand_human_record_path(@system_case), :html => { :class => 'form-horizontal' } do |f| %>
	
	<%= hidden_field_tag :human_record_id, @human_record.id %>

	<h1>Asistencia Legal</h1>

	<hr />

	<h3>Datos</h3>

	<dl class="dl-horizontal">
	  <dt><strong>Caso:</strong></dt>
	  <dd><%= link_to "##{@human_record.system_case.id}", system_case_path(@human_record.system_case) %></dd>
	  <dt><strong>Nombre:</strong></dt>
	  <dd><%= @human_record.human.full_name %></dd>
	  <dt><strong>Sexo:</strong></dt>
	  <dd><%= @human_record.human.sex_name %></dd>
	  <dt><strong>Edad:</strong></dt>
	  <dd><%= @human_record.human.age %></dd>
	</dl>
	
	<dl class="dl-horizontal">
	  <dt><strong>Municipio:</strong></dt>
	  <dd><%= @human_record.system_case.city.name %></dd>
	  <dt><strong>Tipo de zona:</strong></dt>
	  <dd><%= @human_record.system_case.zone_kind.name %></dd>
	  <dt><strong>Fecha de agresion:</strong></dt>
	  <dd><%= @human_record.system_case.aggression_date.strftime("%d/%m/%Y") %></dd>
	  <dt><strong>Reincidencia:</strong></dt>
	  <dd><%= @human_record.system_case.recidivism ? "Si" : "No" %></dd>
	  <dt><strong>Denuncia:</strong></dt>
	  <dd><%= @human_record.system_case.complaint ? "Si" : "No" %></dd>
	</dl>

	<hr /> 

	<h3>Involucrados</h3>

	<%= f.fields_for :human_records do |builder| %>
	  <%= render :partial => 'human_record', :locals => { f: builder } %>
	<% end %>

  	<%= link_to_add_fields "Agregar involucrado", f, :human_records %>

	<div class="form-actions">
		<%= f.button :submit, "Guardar", :class => 'btn-primary' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	            system_cases_path, :class => 'btn' %>
	</div>
<% end %>

app/views/human_records/demand_status.html.erb
OK

app/views/human_records/heal_injuries.html.erb
<h1>HumanRecords#heal_injuries</h1>
<p>Find me in app/views/human_records/heal_injuries.html.erb</p>

app/views/human_records/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Casos Activos" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Victima</th>
      <th>Departamento</th>
      <th>Municipio</th>
      <th>Estado</th>
      <th>Presentacion</th>
      <th>Asistencia</th>
      <th>Estado</th>
    </tr>
  </thead>
  <tbody>
    <% @human_records.each do |human_record| %>
      <tr>
        <td><%= human_record.id %></td>
        <td><%= human_record.human.full_name %></td>
        <td><%= human_record.city.state.name rescue "" %></td>
        <td><%= human_record.city.name rescue "" %></td>
        <td><%= human_record.translate_state %></td>
        <td><%= human_record.system_case.created_at.strftime("%d/%m/%Y") %></td>
        <td>
          <% if can?(:give_legal_advice, HumanRecord) && human_record.legal_attention? %>
              <%= link_to t('.edit', :default => "Legal"), demand_human_record_path(human_record), :class => 'btn btn-mini' %>
          <%end%>

          <%if can?(:do_psico_diagnosis, HumanRecord) && (human_record.psicological_attention? || human_record.psicological_crisis?) %>
            <%= link_to t('.edit', :default => "Psicologica"), active_listening_human_record_path(human_record), :class => 'btn btn-mini' %>
          <% end %>

          <%if can?(:do_med_diagnosis, HumanRecord) && human_record.medical_attention? %>
            <%= link_to t('.edit', :default => "Medica"), heal_injuries_human_record_path(human_record),:method=>:put, :class => 'btn btn-mini' %>
          <% end %>     
        </td>
        <td>
          <%= link_to t('.edit', :default => "Estado"), actual_status_human_record_path(human_record), :class => 'btn btn-mini' %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/human_records/victim_stabilized.html.erb
<h1>HumanRecords#victim_stabilized</h1>
<p>Find me in app/views/human_records/victim_stabilized.html.erb</p>