config/routes.rb
Fosalud::Application.routes.draw do

  get "reports/index"
  match "/view_reports" => "reports#index", :as => "view_reports"

  get "reports/type_reports"
  match "reports/type_reports/:kind/:title" => "reports#type_reports", :as => "type_reports"

  get "reports/aggressions_by_state"
  match "reports/aggressions_by_state/:kind/:title" => "reports#aggressions_by_state" , :as =>"aggressions_by_state"
  resources :aggression_cases

  resources :human_conditions

  resources :human_records, :only=>[:index] do
    member do
      put  "victim_stabilized"
      get  "active_listening" => "human_records#active_listening"
      put "active_listening" => "human_records#active_listening_perform"
      put  "heal_injuries"
      get :demand
      put :demand, :action => :demand_perform
      get :demand
      put :demand, :action => :demand_perform
      get :actual_status
    end
  end

  resources :humen

  resources :violence_kinds

  resources :system_cases

  resources :incident_kinds

  resources :physical_conditions

  resources :psycho_physio_alterations

  resources :emotional_conditions

  resources :weapon_kinds

  resources :aggression_kinds

  resources :zone_kinds

  resources :ocupations

  resources :civil_states

  resources :pregnancy_states

  resources :educational_levels

  resources :human_documents

  resources :document_types

  resources :cities

  resources :states

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  resources :levels
  resources :roles

  get "main/index"

  root :to => 'main#index'

end

app/models/violence_kind.rb
class ViolenceKind < ActiveRecord::Base

  has_many :human_records

  attr_accessible :name
  validates :name,  :presence => true, :uniqueness => true

  def self.all_except_victim
  	where("id <> 1")
  end
  
end

app/controllers/violence_kinds_controller.rb
class ViolenceKindsController < ApplicationController
  # GET /violence_kinds
  # GET /violence_kinds.json
  def index
    @violence_kinds = ViolenceKind.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @violence_kinds }
    end
  end

  # GET /violence_kinds/1
  # GET /violence_kinds/1.json
  def show
    @violence_kind = ViolenceKind.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @violence_kind }
    end
  end

  # GET /violence_kinds/new
  # GET /violence_kinds/new.json
  def new
    @violence_kind = ViolenceKind.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @violence_kind }
    end
  end

  # GET /violence_kinds/1/edit
  def edit
    @violence_kind = ViolenceKind.find(params[:id])
  end

  # POST /violence_kinds
  # POST /violence_kinds.json
  def create
    @violence_kind = ViolenceKind.new(params[:violence_kind])

    respond_to do |format|
      if @violence_kind.save
        format.html { redirect_to @violence_kind, notice: 'Violence kind was successfully created.' }
        format.json { render json: @violence_kind, status: :created, location: @violence_kind }
      else
        format.html { render action: "new" }
        format.json { render json: @violence_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /violence_kinds/1
  # PUT /violence_kinds/1.json
  def update
    @violence_kind = ViolenceKind.find(params[:id])

    respond_to do |format|
      if @violence_kind.update_attributes(params[:violence_kind])
        format.html { redirect_to @violence_kind, notice: 'Violence kind was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @violence_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /violence_kinds/1
  # DELETE /violence_kinds/1.json
  def destroy
    @violence_kind = ViolenceKind.find(params[:id])
    @violence_kind.destroy

    respond_to do |format|
      format.html { redirect_to violence_kinds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/violence_kinds_helper.rb
module ViolenceKindsHelper
end

app/views/violence_kinds/_form.html.erb
<%= simple_form_for @violence_kind, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                violence_kinds_path, :class => 'btn' %>
  </div>
<% end %>

app/views/violence_kinds/edit.html.erb
<%- model_class = ViolenceKind -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/violence_kinds/index.html.erb
<%- model_class = ViolenceKind -%>
<div class="page-header">
  <h1><%#=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <h1>Roles de Casos</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @violence_kinds.each do |violence_kind| %>
      <tr>
        <td><%= link_to violence_kind.id, violence_kind_path(violence_kind) %></td>
        <td><%= violence_kind.name %></td>
        <td><%=l violence_kind.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_violence_kind_path(violence_kind), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      violence_kind_path(violence_kind),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_violence_kind_path,
            :class => 'btn btn-primary' %>

app/views/violence_kinds/new.html.erb
<%- model_class = ViolenceKind -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/violence_kinds/show.html.erb
<%- model_class = ViolenceKind -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @violence_kind.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              violence_kinds_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_violence_kind_path(@violence_kind), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              violence_kind_path(@violence_kind),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>