config/routes.rb
Fosalud::Application.routes.draw do

  get "reports/index"
  match "/view_reports" => "reports#index", :as => "view_reports"

  get "reports/type_reports"
  match "reports/type_reports/:kind/:title" => "reports#type_reports", :as => "type_reports"

  get "reports/aggressions_by_state"
  match "reports/aggressions_by_state/:kind/:title" => "reports#aggressions_by_state" , :as =>"aggressions_by_state"
  resources :aggression_cases

  resources :human_conditions

  resources :human_records, :only=>[:index] do
    member do
      put  "victim_stabilized"
      get  "active_listening" => "human_records#active_listening"
      put "active_listening" => "human_records#active_listening_perform"
      put  "heal_injuries"
      get :demand
      put :demand, :action => :demand_perform
      get :demand
      put :demand, :action => :demand_perform
      get :actual_status
    end
  end

  resources :humen

  resources :violence_kinds

  resources :system_cases

  resources :incident_kinds

  resources :physical_conditions

  resources :psycho_physio_alterations

  resources :emotional_conditions

  resources :weapon_kinds

  resources :aggression_kinds

  resources :zone_kinds

  resources :ocupations

  resources :civil_states

  resources :pregnancy_states

  resources :educational_levels

  resources :human_documents

  resources :document_types

  resources :cities

  resources :states

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  resources :levels
  resources :roles

  get "main/index"

  root :to => 'main#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  def index
  	#@data = get_report("aggressions_by_state")
  	#@data = get_report("aggressions_by_age")
  	@data = get_report("aggressions_by_state_and_age")
  end

  def type_reports
    @data = get_report(params[:kind])
    @title = params[:title].to_s
  end

  def aggressions_by_state
    @data = get_report(params[:kind])
    @title = params[:title].to_s
  end
  # def load_new_report
  # 	@data = get_report(params[:report])
  # end

  def get_report(kind)
  	data = case kind
  		when "aggressions_by_state"
  			SystemCase.aggressions_by_state
  		when "aggressions_by_city"
  			SystemCase.aggressions_by_city
  		when "aggressions_by_age"
  			SystemCase.aggressions_by_age
  		when "aggressions_by_state_and_age"
  			SystemCase.aggressions_by_state_and_age
  		when "aggressions_by_city_and_age"
  			SystemCase.aggressions_by_city_and_age
  		when "aggressions_by_month"
  			SystemCase.aggressions_by_month
  		when "aggressions_by_weekdays"
  			SystemCase.aggressions_by_weekdays  		
  	end

  	return data
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_aggressions_by_state.html.erb
<div class="container_chart">

<table>
	<tr>
		<td>Edad</td><td>Total</td>
		<% categories = []%>
		<% items_age = []%>
        <% state_problem =[]%>
		<% @data.each do |item| %>
			<%categories.push(item.label) %>
			<%items_age.push(item.total)%>
             <% state_problem.push(item.label2)%>
				<%#= item.label.to_s%>
				<!-- <td><%#= item.label2.to_s%></td> -->
				<%#= item.total.to_s%>
		<% end %>
		<hr>
	</tr>
</table>

<%#= categories%>
<%#= items_age%>
<%#= state_problem%>
<div class="clear"></div>


<div id="container_grafics" style="min-width: 400px; height: 400px; margin: 0 auto"></div>

<script type="text/javascript">
var item_categories = [];
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container_grafics',
                type: 'line',
                marginRight: 130,
                marginBottom: 25
            },
            title: {
                text: '<%= @title%>',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
            	title: {
            		text: 'Años'
            	},
                categories: "<%= categories%>"
                // categories: function(){
                // 	for (var i = 0; i > 100; i++) {
                // 		item_categories.push[i]
                // 	};
                	
                // }
            },
            yAxis: {
                title: {
                    text: 'Cantidad'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                        this.x +': '+ this.x +" Personas";
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 100,
                borderWidth: 0
            },
            series: [{
                name: '<%= state_problem[0]%>',
                data: <%= items_age%>
            }]
        });
    });
    
});
console.log(item_categories)
</script>
</div>

app/views/reports/_chart.html.erb
label - total<br />
<% @data.each do |item| %>
	<%#= item.label.to_s + " - " + item.total.to_s %>
	<%= item.label.to_s + " - " + item.label2.to_s + " - " + item.total.to_s %>
	<br />
<% end %>

app/views/reports/aggressions_by_state.js.erb
$("div#container_chart").html("<%= j render 'reports/aggressions_by_state'%>");
setTimeout(function() {
	$('div.container_chart','div#container_chart').fadeIn();
}, 50);

height_content_div();

app/views/reports/index.html.erb
<div id="chart">
	<div class="page-header">
  		<h1>Graficas Generales</h1>
	</div>
	<div class="links_reports">
		<ul id="type_reports">
			<li>
				<%= link_to "Agresiones por Edad", type_reports_path("aggressions_by_age","Cantidad de Agresiones por edad"), :class =>"reports_links btn btn-primary" , :remote => true%>
			</li>
			<li>
				<%= link_to "Agresiones por Departamento", aggressions_by_state_path("aggressions_by_state_and_age","Cantidad de Agresiones por Departamento"), :class =>"reports_links btn btn-primary" , :remote => true%>
			</li>
		</ul>
	</div>
	<div id="container_chart">
	</div>
</div>

app/views/reports/load_new_report.js.erb
$("#chart").html("<%=j <%= render 'chart' %> %>")

app/views/reports/type_reports.js.erb
$("div#container_chart").html("<%= j render 'reports/chart'%>");
setTimeout(function() {
	$('div.container_chart','div#container_chart').fadeIn();
}, 50);
height_content_div();